package LLD.DesignPatterns.structural;

public class AdapterDesignPattern {
    public static void main(String[] args) {
        PaymentAdapter paymentAdapter =  new ProcessDebitCardPayments();
        paymentAdapter.processPayment();
    }
}

// Use case 1. payment Gateway to process different payment providers using adapters
// for Example - PhonePay, G-pay,Debit card, Credit card etc.

// use case extension -
//              - after payment is made the bill generated by provider is in XML but client support json only
//              - to support this we need to create an adapter - xmlToJsonConversionAdapter

class ProcessPhonePayments extends XmlToJsonConvertorAdapter implements PaymentAdapter{
    @Override
    public void processPayment() {
        System.out.println("Processing Phone Pay Payment");
        // after process convert the xml to json
        convertXmlToJson();
    }
    // process phone Pay payments
}

class ProcessGooglePayPayments extends XmlToJsonConvertorAdapter implements PaymentAdapter{
    @Override
    public void processPayment() {
        System.out.println("Processing Google Pay Payment");
        convertXmlToJson();
    }
}

class ProcessDebitCardPayments extends XmlToJsonConvertorAdapter implements PaymentAdapter{
    @Override
    public void processPayment() {
        System.out.println("Processing Debit Card Payment");
        convertXmlToJson();
    }
}

class ProcessCreditCardPayments extends XmlToJsonConvertorAdapter implements PaymentAdapter{
    @Override
    public void processPayment() {
        System.out.println("Processing Credit Card Payment");
        convertXmlToJson();
    }
}


// Common Adapter to support all payment providers
interface PaymentAdapter{
    void processPayment();
}

class XmlToJsonConvertorAdapter{
    public void convertXmlToJson(){
        System.out.println("Data converted to json");
    }
}



